export const GET_ALL_UTILISATEUR = 'GET_ALL_UTILISATEUR';
export const ADD_NEW_UTILISATEUR='ADD_NEW_UTILISATEUR'
export const GET_UTILISATEUR_BY_CODE='GET_UTILISATEUR_BY_CODE'
export const DELETE_UTILISATEUR='DELETE_UTILISATEUR'
export const EDIT_UTILISATEUR='EDIT_UTILISATEUR'
