// Actions pour les statistiques
export const FETCH_STATISTIQUES_REQUEST = 'FETCH_STATISTIQUES_REQUEST';
export const FETCH_STATISTIQUES_SUCCESS = 'FETCH_STATISTIQUES_SUCCESS';
export const FETCH_STATISTIQUES_FAILURE = 'FETCH_STATISTIQUES_FAILURE';