export const SHOW_ASIDE_ADD_MODE_MODULE = "SHOW_ASIDE_ADD_MODE_MODULE";
export const CLOSE_ASIDE_MODULE = "CLOSE_ASIDE_MODULE";
export const RESET_ASIDE_MODULE = "RESET_ASIDE_MODULE";
export const SHOW_ASIDE_EDIT_MODE_MODULE = "SHOW_ASIDE_EDIT_MODE_MODULE";
export const SHOW_ASIDE_DELETE_MODE_MODULE = "SHOW_ASIDE_DELETE_MODE_MODULE";
export const SHOW_ASIDE_CONSULT_MODE_MODULE = "SHOW_ASIDE_CONSULT_MODE_MODULE";
export const SHOW_MODAL_CONFIRMATION_MODULE = "SHOW_MODAL_CONFIRMATION_MODULE";
export const CLOSE_MODAL_CONFIRMATION_MODULE = "CLOSE_MODAL_CONFIRMATION_MODULE";