// Constantes pour le panneau latéral
export const SHOW_ASIDE_ADD_MODE_DEMANDE = 'SHOW_ASIDE_ADD_MODE_DEMANDE';
export const SHOW_ASIDE_EDIT_MODE_DEMANDE = 'SHOW_ASIDE_EDIT_MODE_DEMANDE';
export const SHOW_ASIDE_DELETE_MODE_DEMANDE = 'SHOW_ASIDE_DELETE_MODE_DEMANDE';
export const SHOW_ASIDE_CONSULT_MODE_DEMANDE = 'SHOW_ASIDE_CONSULT_MODE_DEMANDE';
export const CLOSE_ASIDE_DEMANDE = 'CLOSE_ASIDE_DEMANDE';
export const RESET_ASIDE_DEMANDE = 'RESET_ASIDE_DEMANDE';

// Constantes pour la modal de confirmation
export const SHOW_MODAL_CONFIRMATION_DEMANDE = 'SHOW_MODAL_CONFIRMATION_DEMANDE';
export const CLOSE_MODAL_CONFIRMATION_DEMANDE = 'CLOSE_MODAL_CONFIRMATION_DEMANDE';