// Constants pour les actions de base
export const GET_ALL_DEMANDES_REQUEST = 'GET_ALL_DEMANDES_REQUEST';
export const GET_ALL_DEMANDES_SUCCESS = 'GET_ALL_DEMANDES_SUCCESS';
export const GET_ALL_DEMANDES_FAILURE = 'GET_ALL_DEMANDES_FAILURE';

export const GET_DEMANDE_BY_CODE_REQUEST = 'GET_DEMANDE_BY_CODE_REQUEST';
export const GET_DEMANDE_BY_CODE_SUCCESS = 'GET_DEMANDE_BY_CODE_SUCCESS';
export const GET_DEMANDE_BY_CODE_FAILURE = 'GET_DEMANDE_BY_CODE_FAILURE';

export const ADD_DEMANDE_REQUEST = 'ADD_DEMANDE_REQUEST';
export const ADD_DEMANDE_SUCCESS = 'ADD_DEMANDE_SUCCESS';
export const ADD_DEMANDE_FAILURE = 'ADD_DEMANDE_FAILURE';

export const UPDATE_DEMANDE_REQUEST = 'UPDATE_DEMANDE_REQUEST';
export const UPDATE_DEMANDE_SUCCESS = 'UPDATE_DEMANDE_SUCCESS';
export const UPDATE_DEMANDE_FAILURE = 'UPDATE_DEMANDE_FAILURE';

export const DELETE_DEMANDE_REQUEST = 'DELETE_DEMANDE_REQUEST';
export const DELETE_DEMANDE_SUCCESS = 'DELETE_DEMANDE_SUCCESS';
export const DELETE_DEMANDE_FAILURE = 'DELETE_DEMANDE_FAILURE';

// Constants pour la gestion des états de l'interface
export const RESET_DEMANDE = 'RESET_DEMANDE';
export const SET_SELECTED_DEMANDE = 'SET_SELECTED_DEMANDE';