export const SHOW_ASIDE_ADD_MODE_POSTE = "SHOW_ASIDE_ADD_MODE_POSTE";
export const CLOSE_ASIDE_POSTE = "CLOSE_ASIDE_POSTE";
export const RESET_ASIDE_POSTE = "RESET_ASIDE_POSTE";
export const SHOW_ASIDE_EDIT_MODE_POSTE = "SHOW_ASIDE_EDIT_MODE_POSTE";
export const SHOW_ASIDE_DELETE_MODE_POSTE = "SHOW_ASIDE_DELETE_MODE_POSTE";
export const SHOW_ASIDE_CONSULT_MODE_POSTE = "SHOW_ASIDE_CONSULT_MODE_POSTE";
export const SHOW_MODAL_CONFIRMATION_POSTE="SHOW_MODAL_CONFIRMATION_POSTE";
export const CLOSE_MODAL_CONFIRMATION_POSTE="CLOSE_MODAL_CONFIRMATION_POSTE";