export const SHOW_ASIDE_ADD_MODE_CLIENT = "SHOW_ASIDE_ADD_MODE_CLIENT";
export const CLOSE_ASIDE_CLIENT = "CLOSE_ASIDE_CLIENT";
export const RESET_ASIDE_CLIENT = "RESET_ASIDE_CLIENT";
export const SHOW_ASIDE_EDIT_MODE_CLIENT = "SHOW_ASIDE_EDIT_MODE_CLIENT";
export const SHOW_ASIDE_DELETE_MODE_CLIENT = "SHOW_ASIDE_DELETE_MODE_CLIENT";
export const SHOW_ASIDE_CONSULT_MODE_CLIENT = "SHOW_ASIDE_CONSULT_MODE_CLIENT";
export const SHOW_MODAL_CONFIRMATION_CLIENT = "SHOW_MODAL_CONFIRMATION_CLIENT";
export const CLOSE_MODAL_CONFIRMATION_CLIENT = "CLOSE_MODAL_CONFIRMATION_CLIENT";